server:
  port: 8888

spring:
  datasource:
    username: arroba
    password:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:food_delivery_db

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Tallinn
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
